### ISSUE TITLE
"Delay_*.node" does not work as intended.（When used with note2cv.node?）

### ISSUE THREAD

**Issue by Jam-boy** [sigboost-inc/midiglue-forum#10]
開発者様へ

こんにちは！
とても刺激的な製品で、とても楽しいです。
応援しております！

さて、掲題につきまして。
添付したフロー「delay_test.flow」をご確認ください。
これはプリセットの「delay.flow」に対し、
「note2cv.node」を追加したものです。
このフローを使ってディレイの動作を確認したところ
ディレイが効かなる事象が見受けられました。
ご確認のほどよろしくお願いいたいます。

■使用環境
PC: Mac 10.13.6（17G6030）
MIDI source: USB HOST(KORG "nano KONTROL2" . LEDの設定は[external])

■再現
・delay_test.flowを活性化します
・Midiglue側のパラメータ設定
    →「OUT：[HOST]」へ設定
    →「Dry：[On]」へ設定
・USB HOST 側から何かしらのnote信号を送ります。
・その結果、押した時にのみLEDが発光（遅延発光なし）
    ※「delay.flow」であれば、上記の手順を実施すると、
       遅延分の発光も確認できます。

以上よろしくお願いいたします。

＝＝＝＝＝＝google Trancelate＝＝＝＝＝＝
For developers

Hello!
It's a very exciting product and a lot of fun.
I support you!

Now, regarding the subject.
Please check the attached flow "delay_test.flow".
This is for the preset "delay.flow",
"Note2cv.node" is added.
After confirming the delay operation using this flow
The phenomenon that the delay works was found.
Thank you for your confirmation.

■ Usage environment
PC: Mac 10.13.6 (17G6030)
MIDI source: USB HOST (KORG "nano KONTROL2". LED setting is [external])

■ Reproduction
・ Activate delay_test.flow
・ Midiglue side parameter setting
    → Set to “OUT: [HOST]”
    → Set to “Dry: [On]”
-Some note signal is sent from the USB HOST side.
・ As a result, the LED emits light only when pressed (no delayed emission)
    * If it is "delay.flow", if you perform the above procedure,
       You can also check the light emission for the delay.

Thank you for your cooperation.

[delay_test.flow.zip](https://github.com/sigboost-inc/midiglue-forum/files/4567055/delay_test.flow.zip)

**Comment by kuguma** [comment]
完璧なIssueの作成ありがとうございます！
問題を調査したところ、特定のノードの組み合わせで問題が発生することを確認しました。
問題は修正済みで、数日中にアップデートにて配信します！
よろしくお願いいたします。

Thank you for creating the perfect Issue!
After investigating the issue, we found that the issue occurred with a particular combination of nodes.
The problem has been fixed and will be delivered as an update in the coming days!
Thank you.

**Comment by Jam-boy** [comment]
ありがとうございます！楽しみです！

Thank you! I'm looking forward to it!

**Comment by kuguma** [comment]
We have released 1.1.2 and supported them. For details, see the release notes.
https://sigboost.audio/midiglue/manual/download/#v112

1.1.2で対応しました！　詳細はリリースノートを御覧ください。
