### ISSUE TITLE
Bug: Pitch bend nodes replace pitch wheel value with -8192.

### ISSUE THREAD

**Issue by koaxofastora** [sigboost-inc/midiglue-forum#11]
**Environment**
PC: osx 10.14.6 
midiglueEditor version: 1.1.2
MIDI source: Arturia Keystep plugged into MIDI IN 1.

**Description**
When I use the pitch wheel on my MIDI controller, midiglue flows using a `bendin` + `bendout` signal path change all MIDI Pitch Wheel message values to -8192. 

**How to reproduce**
See the files in [pitchbendbug.zip](https://github.com/sigboost-inc/midiglue-forum/files/4674199/pitchbendbug.zip): `workingpitchbend.flow` passes Pitch Wheel messages correctly. `brokenpitchbend.flow` passes Pitch Wheel messages but replaces the values with -8192.

**Comment by kuguma** [comment]
I checked the firmware and identified the issue. Thanks for telling me the problem!
This will be fixed in the next update.

**Comment by kuguma** [comment]
This issue has been fixed in midiglue Editor v1.1.5. Thank you for your report!
