### ISSUE TITLE
How to view debug logging?

### ISSUE THREAD

**Issue by koaxofastora** [sigboost-inc/midiglue-forum#12]
I want to use the Debug API described here: https://sigboost.audio/midiglue/manual/customnode/#debug-api. After I call `Midiglue::Debug::write_log`, how do I view the logging?

**Comment by kuguma** [comment]
Please refer to this page!

https://sigboost.audio/midiglue/manual/body/#_13

Thank you for your question. I will also add it to the API reference page.

**Comment by koaxofastora** [comment]
Thanks. One reason I didn't notice the information at https://sigboost.audio/midiglue/manual/body/#_13 the first time is because of the way it is translated into English by Google. Because `systemボタン長押し` is quoted, it does not get translated. I understood after pasting the last part into Google Translate manually.

**Comment by kuguma** [comment]
Ooops, I'm really sorry about that. I will fix the documentation immediately!
Thank you for your information, I will close the ticket.
