### ISSUE TITLE
MIDI CC#2をCC#20へconvertするprogramを教えていただけますでしょうか。

### ISSUE THREAD

**Issue by ghost** [sigboost-inc/midiglue-forum#14]
MIDIでEWI4000sのbreath controllerからUNO SYNTHのfilter cut off frequencyをcontrolしたいのです。
以前Twitterでヒントをいただきましたがうまくできませんでした。
なんとか教えていただけませんでしょうか。

**Comment by kuguma** [comment]
問い合わせ頂いたアカウントを消されてしまったご様子なので、CC番号などの要件をもう一度教えていただけませんか？

**Comment by ghost** [comment]
ご連絡ありがとうございます。
CC#2をCC#20に変換したいのです。
EWI4000sのブレスセンサーは#2にはアサインできますが#20にはできないのです。
このプログラムがあれば応用で多くのMIDI IN付きシンセサイザーをコントロールでき、EWI4000sユーザーはとても喜びます。
何とぞよろしくお願い申し上げます。

**Comment by kuguma** [comment]
ありがとうございます。

実際に動かして試してはいませんが、次のようなflowで実現できると思います。
（パラメータの値などはzip内のflowをご確認ください。）

![image](https://user-images.githubusercontent.com/1848838/100420382-b2b99a80-30c9-11eb-9674-1117f56b2063.png)
[cc_remap.zip](https://github.com/sigboost-inc/midiglue-forum/files/5606377/cc_remap.zip)

ctrlinでmidipacketを分解し、eqでコントロールナンバーを調べて、#2に一致するときは20を、そうでないときは元々の値を出力するようにしています。

確かにCCの扱いはノードがあまり充実していないように思えるので、拡張を検討してみますね。

**Comment by MakiShira** [comment]
ありがとうございます。
明日仕事明けで家に帰ったらさっそく試してみます。
うまくいったらこれをTwitterで公開したいのですがよろしいでしょうか？

**Comment by ghost** [comment]
さっそく試したところ、希望通りに動きました。
本当にありがとうございます。
世界中のEWI4000sユーザーが待ち望んでいる機能だと思いますので、何らかの形で公開されてはいかがでしょうか。
私もTwitterでこのフォーラムを宣伝したいと思います。

**Comment by kuguma** [comment]
動作されたようでよかったです！
