### ISSUE TITLE
Setup SDcard fails and "midiglue is not connected." is displayed.

### ISSUE THREAD

**Issue by shigobu** [sigboost-inc/midiglue-forum#2]
SDカードを挿入し、midiglueでフォーマットした後、PC(Windows)へ接続しました。
midiglue-Editorから「Setup SDcard」を選択したところ、「midiglue is not connected.」と表示され、正常に終了しません。

デバイスマネージャーを見ると、正常に接続されてることがわかります。
midiを使うアプリケーションでも、midiデバイスとして表示されます。

SDカードは、SanDisk Ultra microSDHC UHS-Iカード16GBです。新品です。

なにか、手順が間違っているのでしょうか？
midiglueは、なにか特別なモードに設定する必要があるのでしょうか？

よろしくおねがいします。

I used Google Translate.

After inserting the SD card and formatting with midiglue, I connected to PC (Windows).
When "Setup SDcard" is selected from midiglue-Editor, "midiglue is not connected." is displayed and it does not end normally.

If you look at the device manager, you can see that it is connected properly.
Applications that use midi will also be displayed as midi devices.

The SD card is SanDisk Ultra microSDHC UHS-I card 16GB. It is new.

What is wrong with the procedure?
Does midiglue need to be set to any special mode?

Thank you very much.

**Comment by kuguma** [comment]
問題の共有ありがとうございます！

通常であれば、midiglueが起動されている状態でそのまま接続してSDカードのセットアップができるはずですが…

先ずは、PC側とmidiglue側のどちらに問題があるのか切り分けをしたいと思います。

- PCの再起動、midiglueの再起動は試してみましたか？
- OSはWindows 10 64bitでしょうか？
- midiglueの初期アプリケーションは動作しますか？（PCや他のデバイスとMIDI信号をやりとりできていますか？）

---

Thank you for sharing the issue!

Normally, you should be able to set up the SD card by connecting as it is while midiglue is running ...

First of all, I would like to categorize whether there is a problem on the PC side or the midiglue side.

-Have you tried restarting your PC or midiglue?
-Is the OS Windows 10 64bit?
-Does the initial application of midiglue work? (Are you able to exchange MIDI signals with your PC or other devices?)

**Comment by shigobu** [comment]
解決しました。

midiglue-Editorを「C:\Program Files」以下に配置していたことが原因でした。
Cドライブ直下に移動したところ、正常に動作しました。
パスに日本語が含まれているとダメだと書いてあったので、「Program Files」に配置したのですが、空白もダメということを見落としていました。
わたしは、ドキュメントフォルダをDドライブに設定しています。そこには、日本語が含まれているので、ドキュメントフォルダに配置しませんでした。

最後に、質問に答えます。
- PCの再起動、midiglueの再起動は何度か実行しました。
- OSはWindows 10 Home(1903) 64bitです。
- midiglueの初期アプリケーションは動作しています。

お騒がせしました。
ありがとうございました。

---
solved.

The cause was that midiglue-Editor was placed under "C: \ Program Files".
When I moved directly under the C drive, it worked normally.
It was written that it was useless if Japanese was included in the path, so I placed it in "Program Files",
I overlooked that the blank was no good.

Finally, answer the questions.
- Restart PC and midiglue several times.
- OS is Windows 10 Home (1903) 64bit.
- The initial application of midiglue is working.

Thank you very much.
