### ISSUE TITLE
midiglue editor: 1buttun compile

### ISSUE THREAD

**Issue by pecosmile** [sigboost-inc/midiglue-forum#3]
sorry, I can't english.

#midiglue 完全に僕のわがまま要望ですが、midiglue editor に、①Reload Node Library、②Ganarate Code、③Compile Flowまでを、一回で実行するショートカットが欲しいです。VS Codeでコーディングしたあと、３回ショートカットを押して確認しなきゃいけないのめんどうです。。

**Comment by kuguma** [comment]
要望をお寄せ頂きありがとうございます！

Google翻訳を使うと、簡単に英訳を作成できますよ。ぜひお試しください。
https://translate.google.co.jp/?hl=ja

F5による転送ショートカットコマンドでは、ご要望の
①Reload Node Library
②Ganarate Code
③Compile Flow
の全てが行われます。勿論、その後midiglueにも転送を試みますが、接続されていなければただ転送に失敗するだけで、それより前の処理はきちんと行われます。

取りあえずは、普段どおり転送ショートカットコマンドを使って頂くというので如何でしょうか？

---

Use the F5 shortcut.
①Reload Node Library
②Ganarate Code
③Compile Flow
④Send binary to midiglue
All these is performed.

**Comment by kuguma** [comment]
上記の方法で問題は解決しましたか？

**Comment by pecosmile** [comment]
ごめんなさい。返答をほうちしてしまいました。
解決、というか、承知しました。
