### ISSUE TITLE
Feature request: Velocity Exponential/Logarithmic Curves Node

### ISSUE THREAD

**Issue by BrufordRules** [sigboost-inc/midiglue-forum#5]
Hi Kai,

I would like to adapt the code in this page to create a MIDI velocity curve node but my knowledge of C++ is almost zero.

https://stackoverflow.com/questions/41134365/formula-to-create-simple-midi-velocity-curves

I can see he used 2 variables
Value: That would be the MIDI velocity and the first input in the Node.
Deviation: That would be the second input in the Node and its default value could be 0 (Linear).

Then with a knob you would send values from -10 to +10 and would get the different logarithmic 
 and exponential curves respectively.

In the code goes from -100 to +100 but I think that -10 to +10 would be enough.

If you make this Node I would really do appreciate it ;-)

Thank you so much in advance.

**Comment by kuguma** [comment]
https://github.com/sigboost-inc/midiglue-forum/issues/9
