### ISSUE TITLE
Feature request: Detect Midi Program Change Messages

### ISSUE THREAD

**Issue by ulilu** [sigboost-inc/midiglue-forum#6]
Hello all @Sigboost,

First of all - thank you very much for creating Midiglue. It took me a while to understand how smart and powerful this little machine really is and, bravo ! you did an excellent job :-)

At the moment I'm using Midiglue to set the routing for my Midi-Mixer (Faderfox UC-44) per Midi channel and it's working very well. 

For my next step, I want to make Midiglue change settings automatically when I load a new song on my external sequencer (Deluge). To do this, I want to create different "signal routings" in Midiglue, that get triggered by Midi-Program-Change-Messages (sent from the Deluge).

I can see that Midiglue understands Midi CC values 0 and 32 (used for "Bank" and "Sub") - however, the "miditype" node does not detect "Midi Program Change" yet.

When I connect the "midilog" node and check the "Debug log", I can see that Program Change messages get received by Midiglue, but they are not yet interpreted. 

I would like to make a feature request: Would it be possible for you to expand the "miditype" node, so that it can also detect "MIDI PC" messages (and their associated values)?

**Comment by kuguma** [comment]
Thank you for your request. 
We will support it with updates within a few days!

**Comment by ulilu** [comment]
Thank you very much for your support! :)

**Comment by kuguma** [comment]
We have released 1.1.2 and supported them. For details, see the release notes.

https://sigboost.audio/midiglue/manual/download/#v112
